In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [ ]:
df = pd.read_csv("train.txt", header=None, sep=";", names=["text", "emotion"])

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

In [5]:
df.duplicated().sum()

np.int64(1)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
df['emotion'] = le.fit_transform(df['emotion'])

In [8]:
df.head()

,text,emotion
0,i didnt feel humiliated,4
1,i can go from feeling so hopeless to so damned...,4
2,im grabbing a minute to post i feel greedy wrong,0
3,i am ever feeling nostalgic about the fireplac...,3
4,i am feeling grouchy,0


# Text clean

* Lowercasing -> "Hello WORLD" → "hello world"
* Remove Punctuation -> "Hello!!!" → "Hello"
* Remove Numbers -> "I have 2 cats" → "I have cats"
* Remove Extra Whitespaces -> "Hello    World" → "Hello World"
* Remove HTML Tags -> "<>Hello</>" → "Hello"
* Remove URLs -> "Visit https://example.com" → "Visit"
* Remove Email Addresses -> "abc@gmail.com" → ""
* Remove Emojis -> "I ❤️ NLP 😊" → "I NLP"
* Remove Special Characters -> "@Hello#$" → "Hello"
* Expand Contractions -> "don't" → "do not"
* Remove Stopwords -> "The cat is sleeping" → "cat sleeping"
* Tokenization -> "I love NLP" -> ["I", "love", "NLP"]
* Stemming -> playing → play studies → studi running → run
* Lemmatization -> running → run better → good studies → study
* Spelling Correction (Optional) -> "machne learnng" → "machine learning"
* Remove Duplicate Words (Optional) -> "good good movie" → "good movie"
* Normalize Text -> "u" → "you" "gr8" → "great"

In [9]:
pip install nltk beautifulsoup4 contractions emoji

Note: you may need to restart the kernel to use updated packages.


In [10]:
import nltk

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

#### 1. Lowercasing

In [11]:
lower_fun = (lambda x:x.lower())

In [12]:
df["text"] = df["text"].apply(lower_fun)

#### 2. Remove Punctuation (. , ! ? : ;)

In [13]:
import string 

def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

In [14]:
df["text"] = df["text"].apply(remove_punc)

### 3. Remove Numbers

In [15]:
import re

# text = "I have 2 cats and 1 dog." 
# # re.sub(pattern, replacement, string)
# re.sub(r"\d+", "", text)

def remove_num(txt):
    return re.sub(r"\d+", "", txt)

In [16]:
df["text"] = df["text"].apply(remove_num)

### 4. Remove Extra Spaces

In [17]:
import re

text = "Hello      World      NLP   "
print(re.sub(r"\s+", " ", text).strip())

def remove_space(txt): 
    return re.sub(r"\s+", " ", txt)

Hello World NLP


In [18]:
df["text"] = df["text"].apply(remove_space)

### 5. Remove HTML Tags

In [19]:
from bs4 import BeautifulSoup

text = "<h1>Hello</h1><p>Welcome to NLP</p>" 
BeautifulSoup(text, "html.parser").get_text()

'HelloWelcome to NLP'

### 6. Remove URLs

In [20]:
import re

text = "Visit https://google.com today."
# Jo bhi text http se start ho ya www se start ho aur next space tak chale, usko match karo.
# \s → whitespace (space, tab, newline)
# \S → NOT whitespace

remove_space(re.sub(r"http\S+|www\S+", "", text))

'Visit today.'

### 7. Remove Email Addresses

In [21]:
import re

text = "Contact me at abc@gmail.com" 
re.sub(r"\S+@\S+|.S+", "", text)

'Contact me at '

### 8. Remove Emojis

In [22]:
import emoji

text = "I ❤️ Python 😊" 
emoji.replace_emoji(text, "")

'I  Python '

### 9. Remove Special Characters

In [23]:
import re

text = "@Hello #Python $100 %Machine^"
re.sub(r"[^a-zA-Z0-9\s]", "", text)

'Hello Python 100 Machine'

### 10. Expand Contractions 

In [24]:
import contractions 

text = "I'm learning NLP. Don't worry."
contractions.fix(text)

'I am learning NLP. Do not worry.'

In [25]:
def expand_contraction(txt): 
    return contractions.fix(txt)

In [26]:
df["text"] = df["text"].apply(expand_contraction)

In [27]:
df["text"].iloc[0]

'i did not feel humiliated'

### 11. Tokenization

In [28]:
from nltk.tokenize import word_tokenize

import nltk
nltk.download('punkt_tab')

text = "I love Machine Learning."
word_tokenize(text)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['I', 'love', 'Machine', 'Learning', '.']

In [29]:
def tokenizing(txt):
    return word_tokenize(txt)

In [30]:
df["text"] = df["text"].apply(tokenizing)

In [31]:
df["text"].iloc[0]

['i', 'did', 'not', 'feel', 'humiliated']

### 12. Remove Stopwords

In [32]:
from nltk.corpus import stopwords
stopwords = set(stopwords.words("english"))

def remove_stopwords(txt):
    return " ".join([word for word in txt if word.lower() not in stopwords])

In [33]:
df["text"] = df["text"].apply(remove_stopwords)

In [34]:
df["text"].iloc[0]

'feel humiliated'

# Bag Of Words

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love Python",
    "I love Machine Learning",
    "Python is amazing"
] 

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(documents)

print("Vocabulary : ")
print(vectorizer.vocabulary_)
print()
print("Features name : ")
print(vectorizer.get_feature_names_out())
print()
print("Bag of Words Matrix:")
print(bow.toarray())

Vocabulary : 
{'love': 3, 'python': 5, 'machine': 4, 'learning': 2, 'is': 1, 'amazing': 0}

Features name : 
['amazing' 'is' 'learning' 'love' 'machine' 'python']

Bag of Words Matrix:
[[0 0 0 1 0 1]
 [0 0 1 1 1 0]
 [1 1 0 0 0 1]]
